controller_manager:
  ros__parameters: # 用于设置控制器管理器的参数
    update_rate: 100 # Hz
    use_sim_time: true  # 使用仿真时间

    # 添加一个控制器节点，用于发布机器人的关节状态
    fishbot_joint_state_broadcaster: # 控制器节点的名称
      type: joint_state_broadcaster/JointStateBroadcaster  # 控制器节点的类型：关节状态广播器

    # 添加一个控制器节点，用于使用力控制器控制机器人的关节
    fishbot_effort_controller:
      type: effort_controllers/JointGroupEffortController  # 控制器节点的类型：力控制器
    
    # 添加一个控制器节点，差速控制器
    fishbot_diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

fishbot_effort_controller:
  ros__parameters:
    joints:
      - left_wheel_joint
      - right_wheel_joint
    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity
      - effort


fishbot_diff_drive_controller:
  ros__parameters:
    left_wheel_names: ["left_wheel_joint"]
    right_wheel_names: ["right_wheel_joint"]

    wheel_separation: 0.2
    wheel_radius: 0.032

    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0

    publish_rate: 50.0
    odom_frame_id: odom
    base_frame_id: base_footprint
    pose_covariance_diagnal: [0.001, 0.001, 0.0, 0.0, 0.0, 0.01]
    twist_covariance_diagnal: [0.001, 0.0, 0.0, 0.0, 0.0, 0.01]

    open_loop: true
    enable_odom_tf: true

    cmd_vel_timeout: 0.5
    # publish_limited_velocity: true
    use_stamped_vel: false
    # velocity_rolling_window_size: 10




