patrol_node:
  ros__parameters:
    initial_point: [0.0, 0.0, 0.0]
    target_points: [
      0.0, 0.0, 0.0,
      1.0, 2.0, 3.14,
      -3.0, 1.5, 1.57,
      -3.0, -2.5, 1.57,
      -2.0, -2.5, 3.14,
      -2.0, 2.0, 3.14,
      0.0, 0.0, 0.0,
      ]
    # image_save_path